### ISSUE TITLE
Add a way to get the value from the textfield out of the alert

### ISSUE THREAD

**Issue by eriksargent** [lightningkite/LKAlertController#16]

**Comment by eriksargent** [comment]
@willia15 let me know what you think about this. I'm wondering if we actually need to modify the add text field method to actually work by passing in a textfield object so the user could set the placeholder, initial value, secure text, keyboard type, etc, and also extract the value from one of the button press closures

**Comment by akwilliamson** [comment]
I think this is a good idea, since there are numerous text field attributes that can be configured.
