### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by akwilliamson** [lightningkite/LKAlertController#21]
What do you think about adding functionality for styling? e.g. adding background color and tint color functionality? I'm not exactly sure what is and is not against the Apple guidelines for alerts.

**Comment by eriksargent** [comment]
I think that's a great idea. If Apple makes it possible to style alerts (I've never tried before) then that support should definitely be added

**Comment by akwilliamson** [comment]
Sounds great, I'll look into what's possible and allowed and start flushing out some ideas.

**Comment by eriksargent** [comment]
Awesome!
