### ISSUE TITLE
Can't invoke addAction(_:style:handler) on ActionSheet instance

### ISSUE THREAD

**Issue by paweljankowski** [lightningkite/LKAlertController#26]
When trying to invoke addAction on ActionSheet class instance with parameters _title_, _style_ and _handler_, Xcode reports:

> Ambiguous use of addAction(_:style:handler)

`ActionSheet().addAction("Test", style: .Default, handler: { _ in print("Test") }).show()` 

I've tried to use LKAlertController instance and it works:

`LKAlertController(style: .ActionSheet).addAction("Test", style: .Default, handler: { _ in print("Test") }).show()`

**Comment by eriksargent** [comment]
Thanks for creating the issue. I've added a test for this issue and updated the code handle it
