### ISSUE TITLE
Attempt to present UIAlertController on view not in the window hierarchy

### ISSUE THREAD

**Issue by afladmark** [lightningkite/LKAlertController#29]
Hiya,

I've been looking for a nice method chain replacement for messy UIAlertController code for a while, so I gave yours a go! Unfortunately, I've run into a problem the first place I've tried to use it. =[  As part of performing Facebook login, I present a very simple dialog when all else fails as follows:

```
Alert(title: "Error", message: "Unable to log in using Facebook. Please check your internet connection and try again.")
.showOkay()
```

This is called as the final part of the async callback chain (when the user has initiated FB login and it fails) and gives me the following error:

Warning: Attempt to present <UIAlertController: 0x7fe3d35df020> on <FBSDKContainerViewController: 0x7fe3d5935af0> whose view is not in the window hierarchy!

I'm guessing that the FBSDKContainer view controller is either being dismissed or isn't the right place to be launching this alert from. I've had a brief look at the logic used to select the controller and it looks sane... but I'm not exactly an expert on this. =/ Not sure where to go from here other than pull it out unless you have any ideas?

Happy to help try and diagnose. I really like the simplicity of your approach.

Kind regards,
Andrew

**Comment by eriksargent** [comment]
The problem is the Facebook login controller is being dismissed at the same time that the alert is being added to be view. To fix it you need to delay the presentation of the alert with `dispatchAfter`. So for example:

```
let delayTime = dispatch_time(DISPATCH_TIME_NOW, Int64(0.3 * Double(NSEC_PER_SEC)))
dispatch_after(delayTime, dispatch_get_main_queue()) {
Alert(title: "Error", message: "Unable to log in using Facebook. Please check your internet connection and try again.")
.showOkay()
}
```

However, it occurs to me that it would be easy to add a `delay` function to LKAlertController to delay the presentation of the alert automatically without all of the nasty boilerplate code that the `dispatchAfter` requires, which is exactly the point of LKAlertController. 

If you're interested in contributing you're more than welcome to create a PR with the delay function that takes he number of seconds to delay for, otherwise I'll add that in a little while. In the meantime though, the `dispatchAfter` should fix your issue. 

Thanks!

**Comment by afladmark** [comment]
Hi Erik,

Thanks for the quick reply. Much appreciated.

If I'm honest, as an approach, timers make me nervous. How long is long enough? How long is too long? What variables impact the time it takes to remove the view? If something delays it, it then just silently fails? Or we make the UI lag a bit longer than we think should ever be necessary, just to be sure... Bleck!

I wonder if another approach might be to allow me to provide a reference to the correct/calling view? In the code I was replacing I was simply calling: `self.presentViewController(alertController, animated: true, completion: nil)` and this seems to "always work". As far as I'm aware anyway. Are there conditions I'm not considering where I'll run into problems anyway and should be adding a buffer?

If the delay is just to support the detection of the currently active view at the time of calling .show(), maybe an extension method to allow the view to be passed in would work? Of course, I have absolutely no sense as to how much of an edge case my situation is. Perhaps I just picked the worst possible place to try it out! I'm lucky like that! ;-P It may be entirely overkill/too much mess if it's a strange situation. Maybe this is just one case I'm best to use a more native solution.

Thanks!

**Comment by eriksargent** [comment]
Thanks for the suggestions, here's what I'm thinking:

I discovered that there is a property on `UIViewController` called `isBeingDismissed`. So I can change the code that will automatically find the top view controller to filter for the top one that is not being dismissed. Hopefully that will provide the most elegant solution.

I'm also going to add a `presentIn(UIViewController)` function so the view controller that the alert should be presented in can be selected. Even if the previous change takes care of the issue for you, I think it will be nice to be able to select where the alert is presented sometimes.

I'm also going to add a `delay(NSTimeInterval)` function. As you point out, timers are definitely not the most elegant solution to your problem, but there may still be some applications where someone wants to delay the alert, and it is really straight forward to add.

I'll update you shortly with the changes. 

Thanks!
Erik

**Comment by afladmark** [comment]
Sounds great. Thanks! I'm happy to help test as well.

**Comment by eriksargent** [comment]
Okay I've made the changes in a separate branch. If you will install it with

```
pod 'LKAlertController', :git => 'https://github.com/LightningKite/LKAlertController.git', :branch => 'AsynchronousPresentation'
```

and do some testing that would be awesome. 

There's a good chance the update will fix the issue without using the new methods, so if you can test that first that would be awesome. I'd also like you to test the `delay` and `presentIn` as well if you can.

Thanks!

**Comment by afladmark** [comment]
You work fast! I've tested all 3 approaches as follows:

`Alert(title: "Error", message: "Unable to log you in using Facebook. Please check your internet connection and try again.")`
`.showOkay()`,
`.presentIn(self).showOkay()`, and
`.delay(10).showOkay()`

All three worked as expected and presented the dialog. I didn't use a stopwatch or anything, but it felt like a long ten seconds for the delay() method. Maybe it's waiting for the view to dismiss and then counting 10s?

**Comment by eriksargent** [comment]
Okay sweet thanks for testing

I've added some testing to verify the delay is delaying the correct time. I'll get this pushed to the cocoapods trunk soon.

**Comment by eriksargent** [comment]
Alright that's been pushed to cocoapods. Thanks for the suggestion and the help testing it!

**Comment by afladmark** [comment]
Happy to help! Thank you for sorting it all out!
