### ISSUE TITLE
Carthage update fails

### ISSUE THREAD

**Issue by JamesPerlman** [lightningkite/LKAlertController#38]
After upgrading to Xcode 8.1 (now with Swift 3.0.1) I had to rebuild LKAlertController, so I used carthage update.  `codesign` failed, and it has something to do with the cocoa pod tests.  

Here are the relevant lines from the carthage-xcodebuild.xxxxxx.log file:

    Signing Identity:     "-"
    
    /usr/bin/codesign --force --sign - --timestamp=none /Users/home/Library/Developer/Xcode/DerivedData/LKAlertController-gfxpomyboovzwidrotfexklagyqa/Build/Products/Release-iphonesimulator/Pods-LKAlertController_Tests/LKAlertController.bundle
    /Users/home/Library/Developer/Xcode/DerivedData/LKAlertController-gfxpomyboovzwidrotfexklagyqa/Build/Products/Release-iphonesimulator/Pods-LKAlertController_Tests/LKAlertController.bundle: bundle format unrecognized, invalid, or unsuitable
    Command /usr/bin/codesign failed with exit code 1

I think the key here is `.../Pods-LKAlertController_Tests/LKAlertController.bundle: bundle format unrecognized, invalid, or unsuitable`

I got around this by forking your repo and removing the Pods-LKAlertController_Tests scheme.

If anyone else needs a hot fix, use 

`github "JamesPerlman/LKAlertController" "patch-1"`

in your Cartfile.

I'm not sure how else to get around this, but I didn't spend too much time trying to figure this out.

Am I the only one who uses Carthage and this framework? :P

**Comment by eriksargent** [comment]
I believe I've figured out the issue and got it fixed. Please let me know if it still doesn't work.
