### ISSUE TITLE
Add simplified Okay alert to simply create an alert with an okay button

### ISSUE THREAD

**Issue by eriksargent** [lightningkite/LKAlertController#6]

**Comment by afladmark** [comment]
Hi Erik,

I wanted to ask a question about this shortcut method. Specifically, why you chose to use "Okay" as opposed to "OK". I realise that I can override this with translations or the like, but the [Apple Human Interface Guidelines for iOS relating to Alerts](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/Alerts.html) seem to recommend the use of OK specifically, for example:

> Use “OK” for a simple acceptance option if there is no better alternative. Avoid using “Yes” or “No.”

I've been blindly using this shortcut method as I've been rolling out your class and have just noticed the inconsistency with other Alert dialogs. So before I go about creating my own methods, or adding the button manually, I guess I just wondered if this was a considered choice, a personal preference, a localisation issue, or just an oversight?

Thanks!
Andrew

**Comment by eriksargent** [comment]
Hi Andrew,

Honestly, I used Okay because the designs I was working from at the time on several different projects used "Okay" rather than "OK". I also prefer the look of "Okay" written out all the way, over "OK", and it still provides a simple acceptance option without the committal of using "Yes" or "No". If you would prefer to use "OK", you can create your own shortcut method really easily in an extension.

```
extension Alert {
    ///Shortcut method for adding an OK button and showing the alert
    public func showOK() {
        addAction("OK", style: .Cancel, preferredAction: false, handler: nil)
        show()
    }
}
```

**Comment by afladmark** [comment]
Thanks, Erik. It's just a convenience method after all, I understand. I'll
use extension methods as you suggest. Thanks for the code!
